### ISSUE TITLE
正文基本属性增加两端对齐

### ISSUE THREAD

**Issue by bridgeQiao** [du33169/typora-theme-essay_cn#1]
Hi,
    这个是写的cn，我就直接用中文了。提一个小建议，在essay.css中，正文基本属性部分，可以加上两端对齐：`text-align: justify;`，显示的行好看一点。
    还有就是`padding`的上部空格感觉太大了，我试了下，设成0.5mm~1mm的话，空间就很大了。
    今天搞了半天，当没有一级标题时，二级标题不能正常编号，修改的地方是
```css
#write {
counter-reset: h2
}
```
但不起作用，toc和侧边栏都可以正常显示，就section不行。如果有什么好的方法请通知下我，谢谢！

**Comment by du33169** [comment]
谢谢你的建议，我会找时间改进；
对于没有上级标题的自动编号，我试了一下，在我这里添加以下样式是可以修复的，不清楚你那边的具体情况：
```css
#write{
    counter-reset: h2 h3 h4;/*修复缺失上级标题时无法递增*/
}
.md-toc-content{
    counter-reset: toc-h2 toc-h3 toc-h4 ;/*修复缺失上级标题时无法递增*/
}
.sidebar-content{
    counter-reset: outline-h2 outline-h3 outline-h4;/*修复缺失上级标题时无法递增*/
}
```
如图：
![Screenshot_20200811_185100](https://user-images.githubusercontent.com/46591250/89889262-e8fb0900-dc03-11ea-87fa-05d1573420e5.png)

**Comment by bridgeQiao** [comment]
没怎么改，但是可以正常对二级标题进行编号了，神奇。
```css
/* 编辑器内标题 */
/** initialize css counter */
#write {
    counter-reset: h2;
}
h1 {
    counter-reset: h2;
}
h2 {
    counter-increment: h2;
    counter-reset: h3;
}
h3 {
    counter-increment: h3;
    counter-reset: h4;
}
h4 {
    counter-increment: h4;
    counter-reset: h5;
}

/** put counter result into headings */

#write h2:before {
    content: counter(h2) ". "
}

#write h3:before {
    content: counter(h2) "." counter(h3) ". "
}

#write h4:before {
    content: counter(h2) "." counter(h3) "." counter(h4) ". "
}
```
